### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#13]
- [x] add app description
- [x] front page?
- [x] #39
- [x] redo the plot (Niko)
- [x] custom colors of the app (Niko)
- [x] logo?
- [x] #19
- [x] #16
- [x] #18
- [x] #22
- [x] #17
- [x] add comoving transverse distance to cmpute
- [x] #20
- [x] #21
- [x] distance modulus (both classic astro and cosmo one - check Hogg's paper)
- [x] naming convention: change r(z) to D_C for the comoving distance (stick with Hogg's notation)
- [x] make rc params?
- [x] upload plot theme notebook with version
- [x] we need to sort the code (it is messy now I think)
- [x] function for the plot? or just leave as is?
- [x] add Hubble time function
- [x] add Hubble distance function

**Comment by nikosarcevic** [comment]
Niko: currently working on the colors

**Comment by nikosarcevic** [comment]
ok so I have played with the logos, this is just a placeholder maybe matthijs can do a better job. we need the logo to blend in the background so the background color needs to be the orange we use in the code. also logo needs to be smaller


tagging @lonbar  and @marcobonici

**Comment by lonbar** [comment]
I've tweaked the letters a bit and added the background colour. We can each have a think about what we want the logo to be in the end.

**Comment by lonbar** [comment]
Regarding citations: we can create an entry in zenodo (https://zenodo.org/), as brought up by @marcobonici in our discussion.
