### ISSUE TITLE
savetxt file issues

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#14]
first we need to decide on the notation standard

 something is off with saving data to txt. seems to be working after I added the comment='' arg but I am experiencing problems when reading the txt file with pandas: 
if I do 
df = pd.read_csv('output.txt') 

then only df['z'] works but does not work for other columns.
solved it by adding df.columns[header string]

we should test this maybe it is my ignorance

**Comment by lonbar** [comment]
I'm not sure I understand what you're saying. Did you solve the problem?

**Comment by lonbar** [comment]
Quoting the header of the output file:
```z, DCz, DMz, DLz, DAz```
So there is a superfluous space for the column headers after  the first one.
