### ISSUE TITLE
export py code?

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#16]

**Comment by lonbar** [comment]
This concerns a function that exports the code for the plots into a `.py` file, right?

**Comment by nikosarcevic** [comment]
> This concerns a function that exports the code for the plots into a `.py` file, right?

id just have it as plain text maybe? or what Robert has let us check that

tagging @marcobonici  as well

**Comment by lonbar** [comment]
You mean the data? We already have a data export feature.

**Comment by nikosarcevic** [comment]
> You mean the data? We already have a data export feature.

no like a block code - for plots

**Comment by nikosarcevic** [comment]
we do not work on this for now

**Comment by nikosarcevic** [comment]
since we are abandoning this, I am going to close the issue
