### ISSUE TITLE
refs

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#18]

**Comment by lonbar** [comment]
@marcobonici what's a good reference for the parametrisation of the dark energy density? Currently we don't provide a reference for that at all, as Hogg's paper doesn't use it.

**Comment by nikosarcevic** [comment]
maybe look up here https://arxiv.org/abs/2110.10074 (shameless plug)

**Comment by marcobonici** [comment]
The first two papers on the CPL parameterization of the dark energy equation of state are (afaik)
[https://arxiv.org/abs/gr-qc/0009008](url)
[https://arxiv.org/abs/astro-ph/0208512](url)

**Comment by lonbar** [comment]
Thanks @nikosarcevic @marcobonici!

**Comment by lonbar** [comment]
Are there any other references that we have used so far? Otherwise I'd close the issue for now.

**Comment by nikosarcevic** [comment]
I think we can close it
