### ISSUE TITLE
lin/log toggle for the plot?

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#19]

**Comment by nikosarcevic** [comment]
ok so I have something. I think we can keep it as an extra plot so you can compare Lin and log.

Thgouhts, @lonbar @marcobonici ?

**Comment by marcobonici** [comment]
I like the possibility to choose between lin and log plots, but I would prefer to keep only a single plot for a couple of reason.

1. It looks to me that the plot page is becoming too much crowded. It's not a problem related to the plot only, it's also about the various options we give to the user. Maybe we can put them in a pop-up menu (as @nikosarcevic did for the tutorial in the main page?).
2. Usually I don't compare the same plot in log and in lin scale: according to the quantity I am interested in, I make the plot in log-log, semi-log or linear scale.

However, for the moment I would keep both the plots, waiting for the moment we will divide all things in more pages in a ordered way.

**Comment by lonbar** [comment]
I'd think it would be nice to have a menu where you indicate what axes you want for your plot, and that the plot is adjusted automatically.

I don't have a very strong opinion about it though; I think it is more important that the data is presented in a clear way.

**Comment by lonbar** [comment]
@nikosarcevic added a toggle for the axes in commit 5a8eabd. Can we close this issue now?
