### ISSUE TITLE
write up about the calculations (Matthijs&Marco?)

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#22]

**Comment by lonbar** [comment]
We'll have to be a bit more specific here. My suggestion would be something along the lines of
### Quantity
**Definition of quantity**
`Equation`

How's that sound @nikosarcevic @marcobonici ?

**Comment by nikosarcevic** [comment]
sounds good to me :)

**Comment by marcobonici** [comment]
Sound good also to me.

**Comment by lonbar** [comment]
First iteration is added in #35.
