### ISSUE TITLE
conversions

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#25]
do we want to also have conversion from pc to ly or m? ned has it not sure if we want that as well

**Comment by marcobonici** [comment]
Yeah, I would add it. Before doing it, I would decide the "look" of the page, such that we now were to put this option.

**Comment by nikosarcevic** [comment]
> Yeah, I would add it. Before doing it, I would decide the "look" of the page, such that we now were to put this option.

oh yes definitely. @lonbar thoughts?

here is the gdoc slides with "ideas" https://docs.google.com/presentation/d/1FGCOEOfd5PCwDRs8lGoHiy4mbk5lvbbcxgsic9Lbdbg/edit?usp=sharing

**Comment by nikosarcevic** [comment]
I have checked and tested the functions and it seems to be ok. closing the issue now
