### ISSUE TITLE
deployment 

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#3]
Hi @lonbar @marcobonici 

it seems there is no easy way of deploying unless we use one of the web app services (like Streamlit or Heroku  or PythonEverywhere.

Can we have an option to make this a python package?  I am not saying we should abandon the web app version.
Just a thought

**Comment by marcobonici** [comment]
I would close this issue.

**Comment by lonbar** [comment]
Yeah, since we've settled on streamlit, this is redundant for now
