### ISSUE TITLE
comoving volume and lookback time plots done

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#31]
ok so I wrote and included the scripts for the volume and lookback time.

added them into the expander on the distances page. however we can discuss if that is a good option or if we can come up with a better way so it is not cluttered (columns? additional pages? or just stick w expand)

**Comment by lonbar** [comment]
For the moment I think that it is fine. If we decide to add more quantities it may be useful to put them on a separate page (to separate the distance measures from other cosmologically interesting stuff).

**Comment by nikosarcevic** [comment]
this is done , im closing the issue
