### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#32]
so when we use plots for comoving,lum etc distances and then I also add to plot the comoving volume and the lookback time in the extender - it reports a problem if we want to plot them all simultaneously. maybe we need to move those plots in a separate page or think about what to do

**Comment by lonbar** [comment]
Just so I understand properly: the app complains if you input all quantities in the same plot?

**Comment by nikosarcevic** [comment]
> Just so I understand properly: the app complains if you input all quantities in the same plot?

yup. just try to plot all at the same time

**Comment by marcobonici** [comment]
Hi @nikosarcevic , could please write here the exact error message?
However, I would put these quantities in separate plots since they have also different units.

**Comment by marcobonici** [comment]
@nikosarcevic maybe I have fixed the bug. The point is that the slider were showing the same text.

**Comment by lonbar** [comment]
It seems to work for me if I tick all the plotting boxes, but the comoving volume and lookback time are each plotted in a separate figure. I thought we wanted to plot everything in one figure?

**Comment by nikosarcevic** [comment]
sorry @marcobonici  I was in the shower

glad you sorted it

@lonbar we do not want to plot everything on one thing as it will get crowded... BUT I mean people can choose what they want to plot? let'S discuss

**Comment by nikosarcevic** [comment]
thanks a lot I will close the issue now
