### ISSUE TITLE
Code coverage badge

### ISSUE THREAD

**Issue by marcobonici** [nikosarcevic/CosmOracle#37]
I'd like to add a badge with the code coverage. While this is not fundamental from our point of view, seeing a badge with the code coverage should increase the users confidence in our tools.

I have opened a separate branch, where I have started working a bit. In particular, I have added the code coverage, In particular, it saves a badge at
`Saved badge to /home/runner/work/CosmOracle/CosmOracle/coverage.svg`

So, probably the problem is just in linking the badge created to the README.

**Comment by nikosarcevic** [comment]
I am actually not even sure what it means but go ahead and do it

**Comment by nikosarcevic** [comment]
link https://betterprogramming.pub/add-badges-to-a-github-repository-716d2988dc6a

**Comment by marcobonici** [comment]
https://github.com/dwyl/repo-badges

**Comment by lonbar** [comment]
I've added a CI badge to the README. It simply indicates that the CI tests pass (not their coverage). Keep in mind that it currently points to the main branch.

**Comment by nikosarcevic** [comment]
> I've added a CI badge to the README. It simply indicates that the CI tests pass (not their coverage). Keep in mind that it currently points to the main branch.

dank je wel, Matthijs

**Comment by marcobonici** [comment]
QUite beautiful! @lonbar , which guide/tutorial did you follow?

**Comment by lonbar** [comment]
Workflow badges are built into GitHub (see [here](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge)). I'm still not sure where coverage stores the badge info.

**Comment by lonbar** [comment]
I've added a coverage badge by hand (commit 03e4d2b). At the moment I think that is the best that we can do.

**Comment by marcobonici** [comment]
Added.
