### ISSUE TITLE
Add dataclass for the cosmological arguments to all the distance functions

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#43]
Suggested by Wessel https://twitter.com/WesselValk/status/1476807736117583892?s=20

**Comment by lonbar** [comment]
We'd be implementing this instead of the yaml file, right?

**Comment by nikosarcevic** [comment]
@marcobonici can you comment?

**Comment by marcobonici** [comment]
Hi!
The point is that the functions we are using receive a lot of arguments, which is not neat and could be error prone.
Having a class containing the values of all cosmological parameters and implementing our functions as claass method would enhance the readibility and mantenability of our code.

**Comment by lonbar** [comment]
So if my understanding is correct, we'd implement something like
````
from dataclasses import dataclass

@dataclass
class cosmoParms:
    redshift: float
    H0: float
    ΩM: float
    ...
````
Then we'd assign the input parameters as `inputParms = cosmoParms(z_value, H0_value, ΩM_value, ...)` and would access these parameters via e.g. `inputParms.redshift`?

**Comment by lonbar** [comment]
I've created an implementation in branch [dataclass](https://github.com/nikosarcevic/CosmOracle/tree/dataclass) (thanks Wessel!). See also #46.
