### ISSUE TITLE
"Calculate" button

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#47]
someone expressed a good feature would be to also have a "calculate" button alongside "press enter to calculate". Do we want this? Pros and cons

**Comment by marcobonici** [comment]
We are gonna close this issue without implementing the calculate button.
This is going to be done for several reasons:

- The sidebar is quite crowded
- It is possible to press "Enter" and obtain the results of calculations from all inputs boxes. If, let's say, we add the "calculate" box on the top and we modify the last parameter, `wa`, we would need to scroll up to the top to press "calculate"
