### ISSUE TITLE
Modify CI trigger

### ISSUE THREAD

**Issue by marcobonici** [nikosarcevic/CosmOracle#50]
Actually the CI is triggered only when we push a commit. However, we it should be possible to trigger the CI also when there is a PR. For instance, someone forked our repo and made a PR, which did not trigger the CI.
What do you think @lonbar @nikosarcevic ?

**Comment by lonbar** [comment]
I've modified the CI workflow in bbb5de6, [per the GitHub documentation](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows). It should now trigger if we get a pull request. Of course, we won't know for sure until someone submits another pull request :shrug:

**Comment by marcobonici** [comment]
Thank you, @lonbar ! I'll close the Issue.
