### ISSUE TITLE
"Object spanning..." calculation seems wrong

### ISSUE THREAD

**Issue by TimothyADavis** [nikosarcevic/CosmOracle#52]
Comparing the results of CosmOracle to cosmocalc (and similar) it seems like the current conversion for the size of an object that subtends 1" is incorrect?

E.g. at z=3 CosmOracle reports "An object spanning an angle of 1 arcsec at redshift 3.0 is therefore 25921.4613 kpc across."  This is clearly incorrect, or we would never manage to resolve z=3 galaxies :-)

Cosmocalc says "The Physical Angular Scale at z is 7.70331 (pkpc/arcsec)" at z=3 with essentially the same cosmological parameters. A rough calculation from the CosmOracle reported angular diameter distance would also predict a value more like 7.8 kpc.  

Perhaps there is a bug in this calculation?

**Comment by nikosarcevic** [comment]
> Comparing the results of CosmOracle to cosmocalc (and similar) it seems like the current conversion for the size of an object that subtends 1" is incorrect?
> 
> E.g. at z=3 CosmOracle reports "An object spanning an angle of 1 arcsec at redshift 3.0 is therefore 25921.4613 kpc across." This is clearly incorrect, or we would never manage to resolve z=3 galaxies :-)
> 
> Cosmocalc says "The Physical Angular Scale at z is 7.70331 (pkpc/arcsec)" at z=3 with essentially the same cosmological parameters. A rough calculation from the CosmOracle reported angular diameter distance would also predict a value more like 7.8 kpc.
> 
> Perhaps there is a bug in this calculation?

Hi, Tim

Thanks for checking this. We only introduced this feature yesterday so it is good you reported back. Much obliged!
We will look into it. Tagging @lonbar and @marcobonici

**Comment by marcobonici** [comment]
Hi @TimothyADavis ! Thank you for pointing this out.

Probably this is an issue related to unit conversions (the given distance is about 3600 times higher than the correct value).
I'll work on this issue this evening.
Thank you again!

**Comment by lonbar** [comment]
Related to #40.

**Comment by marcobonici** [comment]
Hi @TimothyADavis ,
As stated before (and as was stated by @lonbar in #40) there was a conversion issue.
Now everything should be fine :smile: (check with Ned Wright calculator).
