### ISSUE TITLE
Different sets of default parameters.

### ISSUE THREAD

**Issue by lonbar** [nikosarcevic/CosmOracle#57]
Another suggestion is to add an option to choose between different sets of default parameters, say one popular among cosmologists (which, in a way, is the current default) and one more tailored to astronomers. If I understood it correctly, the astronomers are more keen to use something called the "70-30-70" cosmology, but a cursory google search didn't give me anything (though I imagine the numbers relate to Hubble-matter-DE?). @nikosarcevic can you verify this?

**Comment by nikosarcevic** [comment]
yes that is correct

**Comment by nikosarcevic** [comment]
ok I was just looking at some astro paper (for myself and found this) - which is exactly what my astro friend was referring t
<img width="589" alt="Screenshot 2022-01-10 at 18 57 24" src="https://user-images.githubusercontent.com/32773944/148823367-c147bd02-db83-4a10-92d8-e50c9cd1df0b.png">
o

**Comment by lonbar** [comment]
And the other parameters are then zero, I take it? Is there a name for this parametrisation?

**Comment by nikosarcevic** [comment]
> And the other parameters are then zero, I take it? Is there a name for this parametrisation?

I guess that is "the standard 70-30-70" cosmology (I did hear that term before). I have no clue what they do about other papers. I mean it is LCDM so id say that the EoS params are as they are now set to default. Then we just need to modify this to have the astronomer option.

also the add the issue what you talked about today if you would be so kind :)

**Comment by lonbar** [comment]
I've added some logic that should make it straightforward to add support for different sets of parameters in commit aa800ad. The YAML file currently contains our old defaults (PLANCK 2018, right?) and the 70-30-70 / 737 cosmology. I'll play around a bit with different Streamlit options to see what would be the best way to add it to the app.

**Comment by lonbar** [comment]
I've added the feature that users can input their preferred cosmological model (currently either Planck 2018 or this 737/70-30-70 cosmology) in commit 25791ce. I'm not very happy with the dropdown menu being writeable, but whatever. That's just aesthetics. 

@nikosarcevic @marcobonici one of the things I want to ask you to think about is how we present all the different menus/fields. Pull a copy of branch `different-defaults` and run it locally to see how it currently looks.

**Comment by nikosarcevic** [comment]
all good, you can make a PR
