### ISSUE TITLE
Accuracy of the calculator

### ISSUE THREAD

**Issue by lonbar** [nikosarcevic/CosmOracle#7]
A useful feature would be that the users can enter the accuracy (number of significant figures or similar) of the quantities that the calculator computes.

**Comment by marcobonici** [comment]
Probably related to #12 .

I would add a higher precision than the standard one, with a higher `limit` than the standard one (which is 50).
The integrals we are interested in are quite simple (from a numerical point of view) and can be computed in ~ milliseconds, hence we can consider putting high precision settings as the standard one.

**Comment by nikosarcevic** [comment]
add the conversion factors in mind @lonbar

**Comment by nikosarcevic** [comment]
<3
