### ISSUE TITLE
streamlit links

### ISSUE THREAD

**Issue by nikosarcevic** [nikosarcevic/CosmOracle#8]
1. https://share.streamlit.io/daniellewisdl/streamlit-cheat-sheet/app.py
2. https://streamlit.io/gallery
3. https://streamlit.io/gallery?category=streamlit-templates
4. ROBERT'S Stuff https://rdzudzar.github.io/distribution_analyser.html

**Comment by nikosarcevic** [comment]
this might be a solution for multiple inputs
https://discuss.streamlit.io/t/best-approach-to-many-inputs/9558

**Comment by nikosarcevic** [comment]
LAYOUT OPTIONS OMG

https://blog.streamlit.io/introducing-new-layout-options-for-streamlit/

**Comment by lonbar** [comment]
I'm closing this issue for the moment; feel free to reopen if there is more to be said.
